INSERT INTO movies VALUES
('001_TA', 'Tron: Ares', './images/movies/tron_ares.jpg', 'Mankind encounters AI beings for the first time when a highly sophisticated programme, Ares, leaves the digital world for a dangerous mission in the real world', 'Sci-Fi', 10, 'PG-13', '2025-10-09', 119, 1, 0, 'English'),
('002_BP2', 'Black Phone 2', './images/movies/bp2.jpg', 'Bad dreams haunt 15-year-old Gwen as she receives calls from the black phone and sees disturbing visions of three boys being stalked at a winter camp', 'Horror/Thriller', 10, 'R21', '2025-10-16', 114, 1, 0, 'English'),
('003_731', '731', './images/movies/731.jpg', 'In Northeast China, dark and mysterious truths unravel about the horrific experimentation on prison inmates conducted at Unit 731', 'Historical', 10, 'R21', '2025-09-18', 125, 1, 0, 'Japanese/Chinese'),
('004_NOC', 'No Other Choices', './images/movies/noc.jpg', 'After years of unemployment, a man creates a unique and dark plan to secure a job, eliminating his competition.', 'Comedy', 10, 'PG-13', '2025-10-23', 139, 1, 0, 'Korean'),
('005_DSIC', 'Demon Slayer: Infinity Castle', './images/movies/dsic.jpg', 'Tanjiro Kamado and other members of the Demon Slayer Corps find themselves in an epic battle at Infinity Castle.', 'Anime', 10, 'PG-13', '2025-08-14', 155, 1, 0, 'Japanese'),
('006_TCLR', 'The Conjuring: Last Rites', './images/movies/tclr.jpg', 'In 1986 paranormal investigators Ed and Lorraine Warren travel to Pennsylvania to vanquish a demon from a family home.', 'Horror/Thriller', 10, 'PG-13', '2025-09-4', 135, 1, 0, 'English'),
('007_JOK2', 'Joker: Folie À Deux', './images/movies/joker2.jpg', 'Joker: Folie À Deux finds Arthur Fleck institutionalised at Arkham awaiting trial for his crimes as Joker. While struggling with his dual identity, Arthur not only stumbles upon true love, but also finds the music that always been inside him.', 'Drama/Thriller', 10, 'NC-16', '2024-10-03', 138, 0, 0, 'English'),
('008_JWC4', 'John Wick: Chapter 4', './images/movies/jwc4.jpg', 'John Wick (Keanu Reeves) uncovers a path to defeating The High Table. But before he can earn his freedom, Wick must face off against a new enemy with powerful alliances across the globe and forces that turn old friends into foes.', 'Action/Thriller', 10, 'M18', '2023-03-23', 170, 0, 0, 'English'),
('009_JWD', 'Jurassic World Dominion', './images/movies/jwd.jpg', 'In the epic conclusion to the Jurassic era, two generations unite for the first time as Chris Pratt and Bryce Dallas Howard are joined by Laura Dern, Jeff Goldblum and Sam Neill in a bold, timely and breathtaking new adventure that spans the globe.', 'Action/Adventure', 10, 'PG-13', '2022-06-09', 147, 0, 0, 'English'),
('010_SMNWH', 'Spider-Man: No Way Home', './images/movies/smnwh.jpg', 'For the first time in the cinematic history of Spider-Man, our friendly neighborhood hero is unmasked and no longer able to separate his normal life from the high-stakes of being a Super Hero. When he asks for help from Doctor Strange the stakes become even more dangerous, forcing him to discover what it truly means to be Spider-Man.', 'Action/Adventure', 10, 'PG', '2021-12-16', 148, 0, 0, 'English'),
('011_SONIC', 'Sonic The Hedgehog', './images/movies/sonic.jpg', 'Sonic and Tom join forces to try and stop the villainous Dr. Robotnik (Jim Carrey) from capturing Sonic and using his immense powers for world domination.', 'Action/Adventure', 10, 'PG', '2020-02-20', 99, 0, 0, 'English'),
('012_AVGEG', 'Marvel Studios Avengers: Endgame', './images/movies/avengers.jpg', 'The grave course of events set in motion by Thanos that wiped out half the universe and fractured the Avengers ranks compels the remaining Avengers to take one final stand in Marvel Studios’ grand conclusion to twenty-two films', 'Action/Adventure', 10, 'PG-13', '2019-04-24', 181, 0, 0, 'English');
